### PR TITLE
Rotatelogs

### PR DESCRIPTION
**Pull request by dciangot**
adding a rotating log for components.

### CODE REVIEW

**Comment by belforte** [comment]
so.. do we rotate in the log handled, or will we use logrotate system utility ?

**Comment by dciangot** [comment]
As we discussed and agreed last week, this new logs will be the complete ones to be referred to, and operators will take care of stderr (log with no timestamps remember) dimensions by cron or w/e.
Other discussion can be moved forward to understand if keeping stderr logs makes sense at all.

**Comment by dciangot** [comment]
ok, just checked logs and I see timestamps in stderr. 
Don't know why I was convinced that they were not there. 
So, I would close this and proceeding with stderr "rotatelogs" instead.

**Comment by belforte** [comment]
reference:  https://github.com/dmwm/AsyncStageout/issues/4237

**Pull request closed without merging**
