### PR TITLE
Include to retrieve the files details to kill. Fix #4446.

### LINKED ISSUE #4446: Add a new view for Killing files
See https://github.com/dmwm/AsyncStageout/issues/4196

### PR DESCRIPTION
**Pull request by HassenRiahi**

### CODE REVIEW

**Comment by HassenRiahi** [comment]
@juztas , could you review?

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
test this please

**Comment by ericvaandering** [comment]
Something is goofy with git, but I'd like to see what happens with a new PR.

**Pull request closed without merging**
