### PR TITLE
Fix ASO monitor

### PR DESCRIPTION
**Pull request by juztas**
With current release on cmsweb it works with this on my VM, but in the future, whenever CRAB3 will not harcode asynctransfer database, this needs to be changed and it should allow both/multiple databases.

### CODE REVIEW

**Comment by belforte** [comment]
when this is merged, open an issue to remember changing to allow multiple databases

**Comment by HassenRiahi** [comment]
@juztas, is this PR fixing the short monitoring link (https://cmsweb.cern.ch/aso-monitor/index.html)? because the long monitoring URL is working fine.

**Comment by dciangot** [comment]
test this please

**Comment by HassenRiahi** [comment]
I am not sure what this patch should fix. As far as I can see both monitoring links of the 2 ASO instances are working fine: 

https://cmsweb.cern.ch/couchdb2/asynctransfer1/_design/monitor/index.html
https://cmsweb.cern.ch/couchdb/asynctransfer/_design/monitor/index.html
 
@juztas

**Comment by juztas** [comment]
@HassenRiahi this fixes short url which we used, but now with multiple databases this is useless

**Comment by HassenRiahi** [comment]
Ok. Closing the pull request for now and we will re-open if needed.

**Pull request closed without merging**
