### PR TITLE
5 most important erlang views

### PR DESCRIPTION
**Pull request by juztas**

### CODE REVIEW

**Comment by juztas** [comment]
Please, @ericvaandering @belforte @vkuznet @geneguvo @HassenRiahi can you review these views? '%' is a comment there I left current javascript views for review.

I tested all views with current asynctransfer database on my VM.

**Comment by geneguvo** [comment]
Thanks for this, Justas!

I have a few comments:
+ On ftscp_all/map.js, it is emitting "lfn" in the value part, while the original emits "[doc.source_lfn, doc.destination_lfn]";
+ In general on some of the case statements you check "_" first. Isn't it the catch anything operator? AFAICT it should always be the latest because erlang checks them sequentially and would therefore never match things like "undefined -> ok";
+ The reduce equivalent of _count function must check the ReReduce. You can use this code: https://github.com/dmwm/WMCore/blob/master/src/couchapps/WMStatsErl/views/requestHistory/reduce.erl.

Otherwise, looks good to me. We should eventually validate it by getting a dump of the production database, running both erlang and javascript versions and diff-ing the output. That's perhaps what you did in your VM?

With this 5 views in erlang, would we still need to wait for the indexing of the other AsyncTransfer views or these are the views we actually care and need to wait for?

**Comment by juztas** [comment]
You were right. Updated pull request by all comments ;)

Yep, of course my database dump is old (~2months), but it should not make any diff. Please, copy new database dump and I will check.

Not yet. There are still 2 views which are really important and I am working on them also.

**Comment by vkuznet** [comment]
Justas,
apart from Diego's comments I want to address another issue with your views.
In a past we had a problem with ACDC database whose index size grown enormously. The reason
for that was usage of LFNs as view keys. Since those fields are unique
the view size starting growing very fast. In your views, I see that you use
workflow and [User, Group, Role, Dest, Source] as keys. How big are those
fields, are they unique or sparse? I really would like to avoid a similar
problem here.
Valentin.

**Comment by juztas** [comment]
So far what I am changing current views from javascript -> erlang. So all views should be the same. These fields are not big, but as you say it might make problem one day...
This would require minimal code changes, I will let Hassen to comment more on that.

Mainly what I read and find out that IO operations are really expensive and those I would like to get rid off. They are in other views, which are not most urgent.

**Comment by geneguvo** [comment]
I think such discussion is not on the scope of this task. Moreover, my impression is that we will never have such a problem with ASO. Anyhow, if we'd worry about the grown of indexes there are other apps/views we should consider reviewing too since they are already bigger than this one.

**Comment by ericvaandering** [comment]
Obviously pylint is not happy with erlang. :-) Eventually I will try to get pylint to only check python files. For now, ignore it.

**Pull request closed without merging**
