### PR TITLE
Futurize stage1

### PR DESCRIPTION
**Pull request by juztas**

### CODE REVIEW

**Comment by juztas** [comment]
This should be ok and not break anything. I did  `futurize -wn --stage1 .` @ericvaandering @HassenRiahi @mmascher

**Comment by juztas** [comment]
@ericvaandering would it be possible to run jenkins also on ASO code?

**Comment by ericvaandering** [comment]
Yeah, I can do that later today, I hope. @mmascher is ASO included in the new RPM you are making for me (not that it strictly needs to be)

**Comment by HassenRiahi** [comment]
@juztas pls could you update the patch.

**Comment by juztas** [comment]
Updated, but first I would suggest to take this: https://github.com/dmwm/AsyncStageout/pull/4463

It fixes all spaces, identations and makes code more readable and after that I can update stage1 futurize

**Comment by juztas** [comment]
it is included in  #4463

**Pull request closed without merging**
