### PR TITLE
only ftscp ERL

### PR DESCRIPTION
**Pull request by juztas**

### CODE REVIEW

**Comment by juztas** [comment]
@HassenRiahi @dciangot we don't want to have this in upcoming cmsweb release ?

**Comment by dciangot** [comment]
@juztas did you tested it right? so we can include it in the next ASO tag and make a pull request for including it in testbed. 

As discussed at the meeting I wouldn't push for a dedicated deployment, just low prio for now.

**Comment by juztas** [comment]
Yes, it was tested

**Comment by HassenRiahi** [comment]
I hope that the performance of javascript view compared to erlang view has been tested by someone else than @dciangot.  The tests performed by @dciangot shows that javascript view performs better than the erlang one. However it seems folks are convinced that in prod it would be the opposite.

**Pull request merged**
