### PR TITLE
Fix Dashboard notifier for new version of stomp

### PR DESCRIPTION
**Pull request by dciangot**
As discussed here: https://github.com/cms-sw/cmsdist/pull/2744

### CODE REVIEW

**Comment by belforte** [comment]
isn't this already in use ? why an open PR ?

**Comment by dciangot** [comment]
it is a fix to that, only patched and not merged

**Comment by belforte** [comment]
that's what I meant. Why was this not merged ? is there a reason other than lack of attention and communication ? Maybe nobody feels responsible for acting on these PR's ? We MUST fix that !!!

**Comment by dciangot** [comment]
I agree, but let me say that the actual workflow is not so functional. For every PR I have to ping you or @mmascher, but you are already overwhelmed by other stuff and it is not a surprise that those situations may happen.
I could maybe open a jira ticket as remind, or I don't know.

**Pull request merged**
