### PR TITLE
Another fix for 'job failed/done' issues

### PR DESCRIPTION
**Pull request by TonyWildish**
The issue seems to be with occasional corrupt output from the monitoring command. If this happens for a very short job, which only gets monitored once before it completes, it can cause loss of file-state information. This is now protected, so should not happen again.

So, please test when you can. Please also make sure that job_logs is set in the config file. By default this will now only log jobs that have corrupt output, so it won't fill the disk and it might give some clue as to why this happens.

### CODE REVIEW

**Comment by HassenRiahi** [comment]
Please @dciangot could you give it a try?

**Comment by dciangot** [comment]
Hi Tony, 
I'm testing it, and I get this (*).
Nothing is passed to Reporter since everything keep failing.

Here (**) a job-log. 

(*)
2015-03-03 11:25:48: ASOMon[17379]: Job 381d426f-8a07-32ac-d1f4-452a54f5996b changed state from undefined to Finished
2015-03-03 11:25:48: ASOMon[17379]: Job: 381d426f-8a07-32ac-d1f4-452a54f5996b, unrecognised file: srm://storm-se-01.ba.infn.it:8444/srm/managerv2?SFN=//cms/store/user/caio_32/my_2cool_dataset/file-6229-332
2015-03-03 11:25:48: ASOMon[17379]: requeue JOBID=381d426f-8a07-32ac-d1f4-452a54f5996b Priority=1425381949 after failed monitoring...
2015-03-03 11:25:48: ASOMon[17379]: Job 2b09fc58-18a6-a067-19c4-463a54f59975 changed state from undefined to Finished
2015-03-03 11:25:48: ASOMon[17379]: Job: 2b09fc58-18a6-a067-19c4-463a54f59975, unrecognised file: srm://t2-srm-02.lnl.infn.it:8443/srm/managerv2?SFN=/pnfs/lnl.infn.it/data/cms/store/user/dciangot_8/my_2cool_dataset/file-4448-475
2015-03-03 11:25:48: ASOMon[17379]: requeue JOBID=2b09fc58-18a6-a067-19c4-463a54f59975 Priority=1425381949 after failed monitoring...

(**)
$VAR1 = bless( {
  'ID' => 'ff91d097-eb40-fe08-29c3-20a954f597e0',
  'JOB_POSTBACK' => undef,
  'SUMMARY' => '',
  'VERBOSE' => 0,
  'TIMESTAMP' => 1425381450,
  'SPACETOKEN' => undef,
  'LOG' => [
    '1425381361 created... 
',
    '1425381450 /data/ASO/async_install_103pre3/current/apps/asyncstageout/Monitor/PHEDEX/Testbed/FakeFTS.pl glite-transfer-status -l  --verbose -s https://fts3-pilot.cern.ch:8443/ ff91d097-eb40-fe08-29c3-20a954f597e0 
',
    '1425381450 Request ID:     ff91d097-eb40-fe08-29c3-20a954f597e0 
',
    '1425381450 Status:         Finished 
',
    '1425381450 Channel:        MADAGASCAR-CERN 
',
    '1425381450 Client DN:      /DC=ch/DC=cern/OU=Borg Units/OU=Users/CN=mmouse/CN=999999/CN=Mickey Mouse 
',
    '1425381450 Reason:         <None> 
',
    '1425381450 Submit time:    2015-03-03 11:15:44 
',
    '1425381450 Files:          1 
',
    '1425381450 Priority:       1 
',
    '1425381450 VOName:         cms 
',
    '1425381450         Done:           1 
',
    '1425381450         Active:         0 
',
    '1425381450         Pending:        0 
',
    '1425381450         Ready:          0 
',
    '1425381450         Canceled:       0 
',
    '1425381450         Failed:         0 
',
    '1425381450         Finishing:      0 
',
    '1425381450         Finished:       0 
',
    '1425381450         Submitted:      0 
',
    '1425381450         Hold:           0 
',
    '1425381450         Waiting:        0 
',
    '1425381450 Verbose logging ends... 
'
  ],
  'FILE_POSTBACK' => undef,
  'FILES' => {
    'srm://node12.datagrid.cea.fr:8446/srm/managerv2?SFN=/dpm/datagrid.cea.fr/home/cms/trivcat/store/temp/user/tizio_46/my_2cool_dataset/file-9907-1593.root' => bless( {
      'TASKID' => undef,
      'DESTINATION' => 'srm://node12.datagrid.cea.fr:8446/srm/managerv2?SFN=/dpm/datagrid.cea.fr/home/cms/trivcat/store/temp/user/tizio_46/my_2cool_dataset/file-9907-1593.root',
      'FROM_NODE' => undef,
      'TIMESTAMP' => undef,
      'MAX_TRIES' => 3,
      'START' => undef,
      'RETRIES' => 0,
      'LOG' => [],
      'RETRY_MAX_AGE' => 3600,
      'CHECKSUM_TYPE' => undef,
      'REASON' => undef,
      'TO_NODE' => undef,
      'DURATION' => undef,
      'WORKDIR' => undef,
      'FILESIZE' => undef,
      'ME' => undef,
      'PRIORITY' => 1000,
      'STATE' => 'undefined',
      'TIMEOUT' => 0,
      'CHECKSUM_VAL' => undef,
      'SOURCE' => 'LFN: /store/temp/user/tizio_46/my_2cool_dataset/file-9907-1593.root'
    }, 'ASO::File' )
  },
  'USERNAME' => 'tizio_46',
  'WORKDIR' => undef,
  'SERVICE' => 'https://fts3-pilot.cern.ch:8443/',
  'FILE_TIMESTAMP' => undef,
  'COPYJOB' => undef,
  'ME' => 'ff91d097-eb40-fe08-29c3-20a954f597e0',
  'FILE_TIMEOUT' => '18000',
  'PRIORITY' => 3,
  'RAW_OUTPUT' => [
    'Request ID:     ff91d097-eb40-fe08-29c3-20a954f597e0
',
    'Status:         Finished
',
    'Channel:        MADAGASCAR-CERN
',
    'Client DN:      /DC=ch/DC=cern/OU=Borg Units/OU=Users/CN=mmouse/CN=999999/CN=Mickey Mouse
',
    'Reason:         <None>
',
    'Submit time:    2015-03-03 11:15:44
',
    'Files:          1
',
    'Priority:       1
',
    'VOName:         cms
',
    '        Done:           1
',
    '        Active:         0
',
    '        Pending:        0
',
    '        Ready:          0
',
    '        Canceled:       0
',
    '        Failed:         0
',
    '        Finishing:      0
',
    '        Finished:       0
',
    '        Submitted:      0
',
    '        Hold:           0
',
    '        Waiting:        0
',
    '  Source:       srm://node12.datagrid.cea.fr:8446/srm/managerv2?SFN=/dpm/datagrid.cea.fr/home/cms/trivcat/store/temp/user/tizio_46/my_2cool_dataset/file-9907-1593.root
',
    '  Destination:  srm://cmsrm-se01.roma1.infn.it:8443/srm/managerv2?SFN=/pnfs/roma1.infn.it/data/cms/store/user/tizio_46/my_2cool_dataset/file-9907-1593
',
    '  State:        Done
',
    '  Retries:      0
',
    '  Reason:       error during  phase: [] 
',
    '  Duration:     0
'
  ],
  'X509_USER_PROXY' => '/data/proxy',
  'STATE' => 'Finished',
  'TIMEOUT' => '72000',
  'TEMP_DIR' => undef
}, 'ASO::Job' );

**Comment by TonyWildish** [comment]
sorry, this one slipped through my radar.

The messages in (*) above show the monitor catching a corruption in the output (notice the missing '.root' on the filenames). The corruption shouldn't happen, and I can't get it in my machine without explicitly faking it, but the code should be protected against that now. You should find that it re-tries monitoring those jobs and, eventually, reports them successfully. Does it attempt to monitor those jobs again later?

The job-log in (**) shows the same symptom, the monitor returned a truncated filename.

We've seen that I can't reproduce the same problems you get when you run the code. Can you give me login access to your test machine and tell me where your software is? I'll try running from your installation and see if I can get anything from that, maybe there's something different about the running environment. I'd need to know where your code is installed and how you set up the environment, thanks.

Cheers,
Tony.

**Comment by HassenRiahi** [comment]
The Monitor is stable now. Closing this pull request since it is too old.

**Pull request closed without merging**
